import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

const messages = {
  en: {
    brand: 'MemoryBox',
    signIn: 'Sign in',
    signUp: 'Create an account',
    register: 'Create account',
    welcome: 'Welcome back',
    createHeading: 'Make room for less forgetting',
    authIntro: 'Your receipts, records, and little things worth keeping.',
    personalArchive: 'YOUR PERSONAL ARCHIVE',
    keepDetails: 'Keep the details that keep life moving.',
    privateByDesign: 'PRIVATE BY DESIGN',
    name: 'Your name',
    email: 'Email address',
    password: 'Password',
    noAccount: 'New to MemoryBox?',
    haveAccount: 'Already have an account?',
    yourSpace: 'YOUR SPACE',
    allSaved: 'All saved',
    reminders: 'Reminders',
    categories: 'Categories',
    addCategory: 'Add category',
    categoryAdded: 'Category added',
    categoryName: 'Category name',
    categoryPlaceholder: 'e.g. Home, Travel',
    categoryPrompt: 'Organize your saved things with categories.',
    cancel: 'Cancel',
    add: 'Add',
    emptyCategories: 'Your categories appear here',
    signOut: 'Sign out',
    appearance: 'Appearance',
    language: 'Language',
    lightMode: 'Switch to light mode',
    darkMode: 'Switch to dark mode',
    english: 'English',
    hebrew: 'עברית',
    yourBox: 'YOUR BOX',
    tagline: 'A LITTLE LESS TO REMEMBER',
    savedThings: 'Your saved things',
    savedSubtitle: 'The useful details, all in one place.',
    comingBack: 'Things to come back to',
    remindersSubtitle: 'A gentle nudge when it matters.',
    addToBox: 'Add to box',
    search: 'Search titles, tags, notes…',
    filterType: 'All types',
    allTypes: 'All types',
    results: 'items',
    recent: 'RECENTLY UPDATED',
    matching: 'MATCHING',
    loading: 'Loading your saved things…',
    nothingFound: 'Nothing found yet',
    searchHint: 'Try another title, tag, or phrase.',
    boxReady: 'Your box is ready',
    firstSave: 'Save a receipt, a link, or a note to get started.',
    addFirst: 'Add your first item',
    comingUp: 'Coming up',
    seeAll: 'See all',
    quietMoment: 'Nothing due soon. A rare quiet moment.',
    atGlance: 'At a glance',
    savedItems: 'Saved items',
    openReminders: 'Open reminders',
    noReminders: 'No reminders yet',
    reminderHint: 'Open a saved item to set a date to revisit it.',
    loadingApp: 'Opening your box…',
    item: 'item',
    details: 'Details',
    type: 'Type',
    date: 'Date',
    category: 'Category',
    tags: 'Tags',
    tagsPlaceholder: 'warranty, kitchen, 2026',
    tagsHint: 'Separate tags with commas',
    description: 'Description',
    descriptionPlaceholder: 'What should future-you know?',
    attachment: 'Attach a file',
    fileHint: 'PDF, JPG, PNG, or WEBP · up to 10 MB',
    editItem: 'Edit saved item',
    saveSomething: 'Save something useful',
    updateArchive: 'UPDATE YOUR ARCHIVE',
    addArchive: 'ADD TO YOUR ARCHIVE',
    title: 'Title',
    titlePlaceholder: 'e.g. Bike shop receipt',
    saveChanges: 'Save changes',
    saveItem: 'Save item',
    saving: 'Saving…',
    edit: 'Edit item',
    delete: 'Delete item',
    close: 'Close',
    related: 'Related items',
    noRelated: 'No related items yet.',
    reminderForItem: 'Reminders',
    reminderTitle: 'Reminder title',
    reminderDate: 'Reminder date',
    addReminder: 'Add reminder',
    completeReminder: 'Complete reminder',
    reopenReminder: 'Mark reminder incomplete',
    saved: 'Saved to your box',
    updated: 'Changes saved',
    deleted: 'Item deleted',
    reminderAdded: 'Reminder added',
    download: 'Download attachment',
    noDetails: 'No extra details',
    confirmation: 'Delete this saved item?',
    loadError: 'Could not load your box',
    saveError: 'Could not save item',
    categoryError: 'Could not create category',
    categorySaveError: 'Your item was saved, but its category could not be created.',
    reminderError: 'Could not update reminder',
    fileError: 'Could not download this file',
    nothingDue: 'Nothing due soon.',
    today: 'Today',
    account: 'Account',
    all: 'All',
    Document: 'Document',
    Receipt: 'Receipt',
    Note: 'Note',
    Link: 'Link',
    Image: 'Image',
    typeDocument: 'Document',
    typeReceipt: 'Receipt',
    typeNote: 'Note',
    typeLink: 'Link',
    typeImage: 'Image',
    noCategory: 'Uncategorized',
    currentLanguage: 'Current language',
    appearanceLabel: 'Theme',
  },
  he: {
    brand: 'MemoryBox',
    signIn: 'כניסה',
    signUp: 'יצירת חשבון',
    register: 'יצירת חשבון',
    welcome: 'טוב שחזרת',
    createHeading: 'מקום קטן לזכור פחות',
    authIntro: 'קבלות, מסמכים וכל הדברים הקטנים שכדאי לשמור.',
    personalArchive: 'הארכיון האישי שלך',
    keepDetails: 'שומרים את הפרטים שעוזרים לחיים להתקדם.',
    privateByDesign: 'פרטיות כברירת מחדל',
    name: 'השם שלך',
    email: 'כתובת אימייל',
    password: 'סיסמה',
    noAccount: 'חדש ב־MemoryBox?',
    haveAccount: 'כבר יש לך חשבון?',
    yourSpace: 'המרחב שלך',
    allSaved: 'כל הפריטים',
    reminders: 'תזכורות',
    categories: 'קטגוריות',
    addCategory: 'הוספת קטגוריה',
    categoryAdded: 'הקטגוריה נוספה',
    categoryName: 'שם הקטגוריה',
    categoryPlaceholder: 'למשל: בית, נסיעות',
    categoryPrompt: 'ארגנו את הפריטים השמורים לפי קטגוריות.',
    cancel: 'ביטול',
    add: 'הוספה',
    emptyCategories: 'הקטגוריות שלך יופיעו כאן',
    signOut: 'יציאה',
    appearance: 'מראה',
    language: 'שפה',
    lightMode: 'מעבר למצב בהיר',
    darkMode: 'מעבר למצב כהה',
    english: 'English',
    hebrew: 'עברית',
    yourBox: 'המרחב שלך',
    tagline: 'קצת פחות לזכור',
    savedThings: 'הדברים השמורים שלך',
    savedSubtitle: 'כל הפרטים החשובים, במקום אחד.',
    comingBack: 'דברים לחזור אליהם',
    remindersSubtitle: 'תזכורת עדינה בדיוק בזמן.',
    addToBox: 'הוספה למרחב',
    search: 'חיפוש בכותרות, בתגיות ובהערות…',
    filterType: 'כל הסוגים',
    allTypes: 'כל הסוגים',
    results: 'פריטים',
    recent: 'עודכנו לאחרונה',
    matching: 'תוצאות עבור',
    loading: 'טוען את הפריטים השמורים…',
    nothingFound: 'לא נמצאו תוצאות',
    searchHint: 'נסו כותרת, תגית או ביטוי אחר.',
    boxReady: 'המרחב שלך מוכן',
    firstSave: 'שמרו קבלה, קישור או פתק כדי להתחיל.',
    addFirst: 'שמירת פריט ראשון',
    comingUp: 'בקרוב',
    seeAll: 'הצגת הכול',
    quietMoment: 'אין תזכורות קרובות. רגע שקט ונדיר.',
    atGlance: 'במבט מהיר',
    savedItems: 'פריטים שמורים',
    openReminders: 'תזכורות פתוחות',
    noReminders: 'עדיין אין תזכורות',
    reminderHint: 'פתחו פריט שמור כדי להוסיף תזכורת.',
    loadingApp: 'פותחים את המרחב שלך…',
    item: 'פריט',
    details: 'פרטים',
    type: 'סוג',
    date: 'תאריך',
    category: 'קטגוריה',
    tags: 'תגיות',
    tagsPlaceholder: 'אחריות, מטבח, 2026',
    tagsHint: 'הפרידו בין תגיות באמצעות פסיקים',
    description: 'תיאור',
    descriptionPlaceholder: 'מה כדאי שתזכרו בהמשך?',
    attachment: 'צירוף קובץ',
    fileHint: 'PDF, JPG, PNG או WEBP · עד 10 MB',
    editItem: 'עריכת פריט שמור',
    saveSomething: 'שמירת משהו שימושי',
    updateArchive: 'עדכון הארכיון',
    addArchive: 'הוספה לארכיון',
    title: 'כותרת',
    titlePlaceholder: 'למשל: קבלה מחנות אופניים',
    saveChanges: 'שמירת שינויים',
    saveItem: 'שמירת פריט',
    saving: 'שומרים…',
    edit: 'עריכת פריט',
    delete: 'מחיקת פריט',
    close: 'סגירה',
    related: 'פריטים קשורים',
    noRelated: 'אין עדיין פריטים קשורים.',
    reminderForItem: 'תזכורות',
    reminderTitle: 'כותרת התזכורת',
    reminderDate: 'תאריך התזכורת',
    addReminder: 'הוספת תזכורת',
    completeReminder: 'סימון התזכורת כהושלמה',
    reopenReminder: 'סימון התזכורת כלא הושלמה',
    saved: 'נשמר במרחב שלך',
    updated: 'השינויים נשמרו',
    deleted: 'הפריט נמחק',
    reminderAdded: 'התזכורת נוספה',
    download: 'הורדת הקובץ המצורף',
    noDetails: 'אין פרטים נוספים',
    confirmation: 'למחוק את הפריט השמור?',
    loadError: 'לא ניתן לטעון את הפריטים',
    saveError: 'לא ניתן לשמור את הפריט',
    categoryError: 'לא ניתן ליצור קטגוריה',
    categorySaveError: 'הפריט נשמר, אך לא ניתן ליצור את הקטגוריה שלו.',
    reminderError: 'לא ניתן לעדכן את התזכורת',
    fileError: 'לא ניתן להוריד את הקובץ',
    nothingDue: 'אין תזכורות קרובות.',
    today: 'היום',
    account: 'חשבון',
    all: 'הכול',
    Document: 'מסמך',
    Receipt: 'קבלה',
    Note: 'פתק',
    Link: 'קישור',
    Image: 'תמונה',
    typeDocument: 'מסמך',
    typeReceipt: 'קבלה',
    typeNote: 'פתק',
    typeLink: 'קישור',
    typeImage: 'תמונה',
    noCategory: 'ללא קטגוריה',
    currentLanguage: 'שפה נוכחית',
    appearanceLabel: 'ערכת נושא',
  },
} as const;

export type Locale = keyof typeof messages;
export type TranslationKey = keyof typeof messages.en;
export type Theme = 'light' | 'dark';

type PreferencesValue = {
  locale: Locale;
  theme: Theme;
  direction: 'ltr' | 'rtl';
  setLocale: (locale: Locale) => void;
  setTheme: (theme: Theme) => void;
  toggleTheme: () => void;
  t: (key: TranslationKey) => string;
};

const PreferencesContext = createContext<PreferencesValue | null>(null);

function readLocale(): Locale {
  return localStorage.getItem('memorybox-locale') === 'he' ? 'he' : 'en';
}

function readTheme(): Theme {
  return localStorage.getItem('memorybox-theme') === 'dark' ? 'dark' : 'light';
}

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(readLocale);
  const [theme, setTheme] = useState<Theme>(readTheme);
  const direction = locale === 'he' ? 'rtl' : 'ltr';
  const t = useCallback((key: TranslationKey) => messages[locale][key], [locale]);
  const toggleTheme = useCallback(() => setTheme((current) => current === 'light' ? 'dark' : 'light'), []);

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = direction;
    document.documentElement.dataset.theme = theme;
    const themeColor = document.querySelector<HTMLMetaElement>('meta[name="theme-color"]');
    if (themeColor) themeColor.content = theme === 'dark' ? '#14211c' : '#f6f8f5';
    localStorage.setItem('memorybox-locale', locale);
    localStorage.setItem('memorybox-theme', theme);
  }, [locale, theme, direction]);

  const value = useMemo<PreferencesValue>(() => ({
    locale,
    theme,
    direction,
    setLocale,
    setTheme,
    toggleTheme,
    t,
  }), [locale, theme, direction, toggleTheme, t]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const value = useContext(PreferencesContext);
  if (!value) throw new Error('usePreferences must be used inside PreferencesProvider');
  return value;
}
